/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_koushikdutta_monodalvikbridge_MonoBridge */

#ifndef _Included_com_koushikdutta_monodalvikbridge_MonoBridge
#define _Included_com_koushikdutta_monodalvikbridge_MonoBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Default
#define com_koushikdutta_monodalvikbridge_MonoBridge_Default 0L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Char
#define com_koushikdutta_monodalvikbridge_MonoBridge_Char 1L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Byte
#define com_koushikdutta_monodalvikbridge_MonoBridge_Byte 2L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Int16
#define com_koushikdutta_monodalvikbridge_MonoBridge_Int16 3L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_UInt16
#define com_koushikdutta_monodalvikbridge_MonoBridge_UInt16 4L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Int32
#define com_koushikdutta_monodalvikbridge_MonoBridge_Int32 5L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_UInt32
#define com_koushikdutta_monodalvikbridge_MonoBridge_UInt32 6L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Int64
#define com_koushikdutta_monodalvikbridge_MonoBridge_Int64 7L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_UInt64
#define com_koushikdutta_monodalvikbridge_MonoBridge_UInt64 8L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Single
#define com_koushikdutta_monodalvikbridge_MonoBridge_Single 9L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Double
#define com_koushikdutta_monodalvikbridge_MonoBridge_Double 10L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Boolean
#define com_koushikdutta_monodalvikbridge_MonoBridge_Boolean 11L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_String
#define com_koushikdutta_monodalvikbridge_MonoBridge_String 12L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_MonoObject
#define com_koushikdutta_monodalvikbridge_MonoBridge_MonoObject 13L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_JavaObject
#define com_koushikdutta_monodalvikbridge_MonoBridge_JavaObject 14L
#undef com_koushikdutta_monodalvikbridge_MonoBridge_Void
#define com_koushikdutta_monodalvikbridge_MonoBridge_Void 15L
/*
 * Class:     com_koushikdutta_monodalvikbridge_MonoBridge
 * Method:    getInvokeBuffer
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_koushikdutta_monodalvikbridge_MonoBridge_getInvokeBuffer
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_koushikdutta_monodalvikbridge_MonoBridge
 * Method:    setReturnBuffer
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_koushikdutta_monodalvikbridge_MonoBridge_setReturnBuffer
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_koushikdutta_monodalvikbridge_MonoBridge
 * Method:    initializeRuntime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_koushikdutta_monodalvikbridge_MonoBridge_initializeRuntime
  (JNIEnv *, jclass);

/*
 * Class:     com_koushikdutta_monodalvikbridge_MonoBridge
 * Method:    invokeInternal
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_koushikdutta_monodalvikbridge_MonoBridge_invokeInternal
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
