/* File automatically generated by genmdesc, don't change */

const char arm_cpu_desc [] = {
	"\x0\x0\x0\x0\x0\x0\x0"	/* null entry */
	"\x0" "\x0" "\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* nop */
	"\x0" "\x0" "\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* relaxed_nop */
	"\x0" "ii\x0" "\x4" "4\x0" "\x0" ""	/* compare */
	"\x0" "i\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* compare_imm */
	"\x0" "ff\x0" "\xc" "\xc" "\x0" "\x0" ""	/* fcompare */
	"\x0" "ii\x0" "\x4" "4\x0" "\x0" ""	/* icompare */
	"\x0" "i\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* icompare_imm */
	"\x0" "f\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* setfret */
	"\x0" "ii\x0" "\xc" "\xc" "\x0" "\x0" ""	/* setlret */
	"ii\x0" "\x0" "\x3c" "\x3c" "\x0" "\x0" ""	/* localloc */
	"\x0" "b\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* checkthis */
	"\x0" "\x0" "\x0" "\x0" "\x26" "\x26" "\x0" "\x0" ""	/* seq_point */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "c\x0" ""	/* voidcall */
	"\x0" "i\x0" "\x0" "\x8" "8c\x0" ""	/* voidcall_reg */
	"\x0" "b\x0" "\x0" "\xc" "\xc" "c\x0" ""	/* voidcall_membase */
	"a\x0" "\x0" "\x0" "\x14" "\x14" "c\x0" ""	/* call */
	"ai\x0" "\x0" "\x8" "8c\x0" ""	/* call_reg */
	"ab\x0" "\x0" "\xc" "\xc" "c\x0" ""	/* call_membase */
	"g\x0" "\x0" "\x0" "\x1c" "\x1c" "c\x0" ""	/* fcall */
	"gi\x0" "\x0" "\x10" "\x10" "c\x0" ""	/* fcall_reg */
	"gb\x0" "\x0" "\x14" "\x14" "c\x0" ""	/* fcall_membase */
	"l\x0" "\x0" "\x0" "\x14" "\x14" "c\x0" ""	/* lcall */
	"li\x0" "\x0" "\x8" "8c\x0" ""	/* lcall_reg */
	"lb\x0" "\x0" "\xc" "\xc" "c\x0" ""	/* lcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "c\x0" ""	/* vcall */
	"\x0" "i\x0" "\x0" "\x8" "8c\x0" ""	/* vcall_reg */
	"\x0" "b\x0" "\x0" "\xc" "\xc" "c\x0" ""	/* vcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "c\x0" ""	/* vcall2 */
	"\x0" "i\x0" "\x0" "\x8" "8c\x0" ""	/* vcall2_reg */
	"\x0" "b\x0" "\x0" "\xc" "\xc" "c\x0" ""	/* vcall2_membase */
	"\x0" "ii\x0" "\x80" "\x80" "c\x0" ""	/* dyn_call */
	"i\x0" "\x0" "\x0" "\x10" "\x10" "\x0" "\x0" ""	/* iconst */
	"f\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* r4const */
	"f\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* r8const */
	"\x0" "\x0" "\x0" "\x0" "\x0" "0\x0" "\x0" ""	/* label */
	"\x0" "i\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* switch */
	"\x0" "i\x0" "\x0" "\x18" "\x18" "\x0" "\x0" ""	/* throw */
	"\x0" "i\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* rethrow */
	"\x0" "i\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* oparglist */
	"bi\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* store_membase_reg */
	"bi\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* storei1_membase_reg */
	"bi\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* storei2_membase_reg */
	"bi\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* storei4_membase_reg */
	"bi\x0" "\x0" "\x0" "\x0" "\x0" ""	/* storei8_membase_reg */
	"bf\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* storer4_membase_reg */
	"bf\x0" "\x0" "\x18" "\x18" "\x0" "\x0" ""	/* storer8_membase_reg */
	"b\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* store_membase_imm */
	"b\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* storei1_membase_imm */
	"b\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* storei2_membase_imm */
	"b\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* storei4_membase_imm */
	"b\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* storei8_membase_imm */
	"ib\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* load_membase */
	"ib\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* loadi1_membase */
	"ib\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* loadu1_membase */
	"ib\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* loadi2_membase */
	"ib\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* loadu2_membase */
	"ib\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* loadi4_membase */
	"ib\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* loadu4_membase */
	"ib\x0" "\x0" "\x0" "\x0" "\x0" ""	/* loadi8_membase */
	"fb\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* loadr4_membase */
	"fb\x0" "\x0" "\x18" "\x18" "\x0" "\x0" ""	/* loadr8_membase */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* load_memindex */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* loadi1_memindex */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* loadu1_memindex */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* loadi2_memindex */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* loadu2_memindex */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* loadi4_memindex */
	"ibi\x0" "\x4" "4\x0" "\x0" ""	/* loadu4_memindex */
	"bii\x0" "\x4" "4\x0" "\x0" ""	/* store_memindex */
	"bii\x0" "\x4" "4\x0" "\x0" ""	/* storei1_memindex */
	"bii\x0" "\x4" "4\x0" "\x0" ""	/* storei2_memindex */
	"bii\x0" "\x4" "4\x0" "\x0" ""	/* storei4_memindex */
	"i\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* loadu4_mem */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* move */
	"ff\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* fmove */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* add_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* sub_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* mul_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* and_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* or_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* xor_imm */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* shl_imm */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* shr_imm */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* br */
	"\x0" "\x0" "\x0" "\x0" "\x5c" "\x5c" "\x0" "\x0" ""	/* jmp */
	"\x0" "\x0" "\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* break */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* ceq */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* cgt */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* cgt.un */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* clt */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* clt.un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_eq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_gt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_le */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_lt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_gt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_le_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_lt_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* cond_exc_ov */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_no */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* cond_exc_c */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_nc */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ieq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ige */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_igt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ile */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ilt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ine_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ige_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_igt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ile_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ilt_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* cond_exc_iov */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_ino */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* cond_exc_ic */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* cond_exc_inc */
	"iii\x0" "\x24" "\x24" "\x0" "\x0" ""	/* long_conv_to_ovf_i4_2 */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_add */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_sub */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_mul */
	"iii\x0" "\x28" "\x28" "\x0" "\x0" ""	/* int_div */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_div_un */
	"iii\x0" "\x30" "\x30" "\x0" "\x0" ""	/* int_rem */
	"iii\x0" "\x18" "\x18" "\x0" "\x0" ""	/* int_rem_un */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_and */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_or */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_xor */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_shl */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_shr */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_shr_un */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* int_neg */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* int_not */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_conv_to_i1 */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_conv_to_i2 */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* int_conv_to_i4 */
	"fi\x0" "\x0" "\x24" "\x24" "\x0" "\x0" ""	/* int_conv_to_r4 */
	"fi\x0" "\x0" "\x24" "\x24" "\x0" "\x0" ""	/* int_conv_to_r8 */
	"ii\x0" "\x0" "\x0" "\x0" "\x0" ""	/* int_conv_to_u4 */
	"fi\x0" "\x0" "\x38" "\x38" "\x0" "\x0" ""	/* int_conv_to_r_un */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_conv_to_u2 */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* int_conv_to_u1 */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_add_ovf */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_add_ovf_un */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_mul_ovf */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_mul_ovf_un */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_sub_ovf */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_sub_ovf_un */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_adc */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_adc_imm */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_sbb */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_sbb_imm */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_addcc */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* int_subcc */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_add_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_sub_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_mul_imm */
	"ii\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* int_div_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_div_un_imm */
	"ii\x0" "\x0" "\x1c" "\x1c" "\x0" "\x0" ""	/* int_rem_imm */
	"ii\x0" "\x0" "\x10" "\x10" "\x0" "\x0" ""	/* int_rem_un_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_and_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_or_imm */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_xor_imm */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_shl_imm */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_shr_imm */
	"ii\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_shr_un_imm */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_ceq */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_cgt */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_cgt_un */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_clt */
	"i\x0" "\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* int_clt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_beq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_bge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_ble */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_blt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* int_blt_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_beq */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_bge */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_ble */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_blt */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_blt_un */
	"fff\x0" "\x4" "4\x0" "\x0" ""	/* float_add */
	"fff\x0" "\x4" "4\x0" "\x0" ""	/* float_sub */
	"fff\x0" "\x4" "4\x0" "\x0" ""	/* float_mul */
	"fff\x0" "\x4" "4\x0" "\x0" ""	/* float_div */
	"fff\x0" "\x4" "4\x0" "\x0" ""	/* float_div_un */
	"fff\x0" "\x10" "\x10" "\x0" "\x0" ""	/* float_rem */
	"fff\x0" "\x10" "\x10" "\x0" "\x0" ""	/* float_rem_un */
	"ff\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* float_neg */
	"ff\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* float_not */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_i1 */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_i2 */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_i4 */
	"lf\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_i8 */
	"ff\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* float_conv_to_r4 */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_u4 */
	"lf\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_u8 */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_u2 */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_u1 */
	"if\x0" "\x0" "\x28" "\x28" "\x0" "\x0" ""	/* float_conv_to_i */
	"iff\x0" "\x10" "\x10" "\x0" "\x0" ""	/* float_ceq */
	"iff\x0" "\x10" "\x10" "\x0" "\x0" ""	/* float_cgt */
	"iff\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_cgt_un */
	"iff\x0" "\x10" "\x10" "\x0" "\x0" ""	/* float_clt */
	"iff\x0" "\x14" "\x14" "\x0" "\x0" ""	/* float_clt_un */
	"if\x0" "\x0" "\x24" "\x24" "\x0" "\x0" ""	/* float_conv_to_u */
	"ff\x0" "\x0" "\x40" "\x40" "\x0" "\x0" ""	/* ckfinite */
	"i\x0" "\x0" "\x0" "\x10" "\x10" "\x0" "\x0" ""	/* aot_const */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\xc" "c\x0" ""	/* call_handler */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* start_handler */
	"\x0" "i\x0" "\x0" "\x10" "\x10" "\x0" "\x0" ""	/* endfilter */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x14" "\x0" "\x0" ""	/* endfinally */
	"lii\x0" "\x8" "8\x0" "\x0" ""	/* bigmul */
	"lii\x0" "\x8" "8\x0" "\x0" ""	/* bigmul_un */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* adc */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* adc_imm */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* sbb */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* sbb_imm */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* addcc */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* addcc_imm */
	"iii\x0" "\x4" "4\x0" "\x0" ""	/* subcc */
	"ii\x0" "\x0" "\xc" "\xc" "\x0" "\x0" ""	/* subcc_imm */
	"\x0" "i\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* br_reg */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* add_ovf_carry */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* sub_ovf_carry */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* add_ovf_un_carry */
	"iii\x0" "\x10" "\x10" "\x0" "\x0" ""	/* sub_ovf_un_carry */
	"ff\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* sqrt */
	"i\x0" "\x0" "\x0" "\x8" "8\x0" "\x0" ""	/* tls_get */
	"\x0" "i\x0" "\x0" "\x0" "0\x0" "\x0" ""	/* dummy_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" "0\x0" "\x0" ""	/* dummy_store */
	"\x0" "\x0" "\x0" "\x0" "\x0" "0\x0" "\x0" ""	/* not_reached */
	"\x0" "i\x0" "\x0" "\x0" "0\x0" "\x0" ""	/* not_null */
	"\x0" "\x0" "\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* memory_barrier */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* arm_rsbs_imm */
	"ii\x0" "\x0" "\x4" "4\x0" "\x0" ""	/* arm_rsc_imm */
};

const guint16 arm_cpu_desc_idx [] = {
	0,	/* load */
	0,	/* ldaddr */
	0,	/* store */
	7,	/* nop */
	0,	/* hard_nop */
	14,	/* relaxed_nop */
	0,	/* phi */
	0,	/* fphi */
	0,	/* vphi */
	21,	/* compare */
	28,	/* compare_imm */
	35,	/* fcompare */
	0,	/* lcompare */
	42,	/* icompare */
	49,	/* icompare_imm */
	0,	/* lcompare_imm */
	0,	/* local */
	0,	/* arg */
	0,	/* outarg_vt */
	0,	/* outarg_vtretaddr */
	0,	/* setret */
	56,	/* setfret */
	63,	/* setlret */
	70,	/* localloc */
	0,	/* localloc_imm */
	77,	/* checkthis */
	84,	/* seq_point */
	0,	/* implicit_exception */
	91,	/* voidcall */
	0,	/* voidcallvirt */
	98,	/* voidcall_reg */
	105,	/* voidcall_membase */
	112,	/* call */
	119,	/* call_reg */
	126,	/* call_membase */
	0,	/* callvirt */
	133,	/* fcall */
	0,	/* fcallvirt */
	140,	/* fcall_reg */
	147,	/* fcall_membase */
	154,	/* lcall */
	0,	/* lcallvirt */
	161,	/* lcall_reg */
	168,	/* lcall_membase */
	175,	/* vcall */
	0,	/* vcallvirt */
	182,	/* vcall_reg */
	189,	/* vcall_membase */
	196,	/* vcall2 */
	203,	/* vcall2_reg */
	210,	/* vcall2_membase */
	217,	/* dyn_call */
	224,	/* iconst */
	0,	/* i8const */
	231,	/* r4const */
	238,	/* r8const */
	0,	/* regvar */
	0,	/* regoffset */
	0,	/* vtarg_addr */
	245,	/* label */
	252,	/* switch */
	259,	/* throw */
	266,	/* rethrow */
	273,	/* oparglist */
	280,	/* store_membase_reg */
	287,	/* storei1_membase_reg */
	294,	/* storei2_membase_reg */
	301,	/* storei4_membase_reg */
	308,	/* storei8_membase_reg */
	315,	/* storer4_membase_reg */
	322,	/* storer8_membase_reg */
	329,	/* store_membase_imm */
	336,	/* storei1_membase_imm */
	343,	/* storei2_membase_imm */
	350,	/* storei4_membase_imm */
	357,	/* storei8_membase_imm */
	0,	/* storex_membase */
	0,	/* storev_membase */
	364,	/* load_membase */
	371,	/* loadi1_membase */
	378,	/* loadu1_membase */
	385,	/* loadi2_membase */
	392,	/* loadu2_membase */
	399,	/* loadi4_membase */
	406,	/* loadu4_membase */
	413,	/* loadi8_membase */
	420,	/* loadr4_membase */
	427,	/* loadr8_membase */
	0,	/* loadx_membase */
	0,	/* loadv_membase */
	434,	/* load_memindex */
	441,	/* loadi1_memindex */
	448,	/* loadu1_memindex */
	455,	/* loadi2_memindex */
	462,	/* loadu2_memindex */
	469,	/* loadi4_memindex */
	476,	/* loadu4_memindex */
	0,	/* loadi8_memindex */
	0,	/* loadr4_memindex */
	0,	/* loadr8_memindex */
	483,	/* store_memindex */
	490,	/* storei1_memindex */
	497,	/* storei2_memindex */
	504,	/* storei4_memindex */
	0,	/* storei8_memindex */
	0,	/* storer4_memindex */
	0,	/* storer8_memindex */
	0,	/* load_mem */
	0,	/* loadu1_mem */
	0,	/* loadu2_mem */
	0,	/* loadi4_mem */
	511,	/* loadu4_mem */
	0,	/* loadi8_mem */
	0,	/* store_mem_imm */
	518,	/* move */
	0,	/* lmove */
	525,	/* fmove */
	0,	/* vmove */
	0,	/* vzero */
	532,	/* add_imm */
	539,	/* sub_imm */
	546,	/* mul_imm */
	0,	/* div_imm */
	0,	/* div_un_imm */
	0,	/* rem_imm */
	0,	/* rem_un_imm */
	553,	/* and_imm */
	560,	/* or_imm */
	567,	/* xor_imm */
	574,	/* shl_imm */
	581,	/* shr_imm */
	588,	/* shr_un_imm */
	595,	/* br */
	602,	/* jmp */
	0,	/* tailcall */
	609,	/* break */
	616,	/* ceq */
	623,	/* cgt */
	630,	/* cgt.un */
	637,	/* clt */
	644,	/* clt.un */
	651,	/* cond_exc_eq */
	658,	/* cond_exc_ge */
	665,	/* cond_exc_gt */
	672,	/* cond_exc_le */
	679,	/* cond_exc_lt */
	686,	/* cond_exc_ne_un */
	693,	/* cond_exc_ge_un */
	700,	/* cond_exc_gt_un */
	707,	/* cond_exc_le_un */
	714,	/* cond_exc_lt_un */
	721,	/* cond_exc_ov */
	728,	/* cond_exc_no */
	735,	/* cond_exc_c */
	742,	/* cond_exc_nc */
	749,	/* cond_exc_ieq */
	756,	/* cond_exc_ige */
	763,	/* cond_exc_igt */
	770,	/* cond_exc_ile */
	777,	/* cond_exc_ilt */
	784,	/* cond_exc_ine_un */
	791,	/* cond_exc_ige_un */
	798,	/* cond_exc_igt_un */
	805,	/* cond_exc_ile_un */
	812,	/* cond_exc_ilt_un */
	819,	/* cond_exc_iov */
	826,	/* cond_exc_ino */
	833,	/* cond_exc_ic */
	840,	/* cond_exc_inc */
	0,	/* long_add */
	0,	/* long_sub */
	0,	/* long_mul */
	0,	/* long_div */
	0,	/* long_div_un */
	0,	/* long_rem */
	0,	/* long_rem_un */
	0,	/* long_and */
	0,	/* long_or */
	0,	/* long_xor */
	0,	/* long_shl */
	0,	/* long_shr */
	0,	/* long_shr_un */
	0,	/* long_neg */
	0,	/* long_not */
	0,	/* long_conv_to_i1 */
	0,	/* long_conv_to_i2 */
	0,	/* long_conv_to_i4 */
	0,	/* long_conv_to_i8 */
	0,	/* long_conv_to_r4 */
	0,	/* long_conv_to_r8 */
	0,	/* long_conv_to_u4 */
	0,	/* long_conv_to_u8 */
	0,	/* long_conv_to_u2 */
	0,	/* long_conv_to_u1 */
	0,	/* long_conv_to_i */
	0,	/* long_conv_to_ovf_i */
	0,	/* long_conv_to_ovf_u */
	0,	/* long_add_ovf */
	0,	/* long_add_ovf_un */
	0,	/* long_mul_ovf */
	0,	/* long_mul_ovf_un */
	0,	/* long_sub_ovf */
	0,	/* long_sub_ovf_un */
	0,	/* long_conv_to_ovf_i1_un */
	0,	/* long_conv_to_ovf_i2_un */
	0,	/* long_conv_to_ovf_i4_un */
	0,	/* long_conv_to_ovf_i8_un */
	0,	/* long_conv_to_ovf_u1_un */
	0,	/* long_conv_to_ovf_u2_un */
	0,	/* long_conv_to_ovf_u4_un */
	0,	/* long_conv_to_ovf_u8_un */
	0,	/* long_conv_to_ovf_i_un */
	0,	/* long_conv_to_ovf_u_un */
	0,	/* long_conv_to_ovf_i1 */
	0,	/* long_conv_to_ovf_u1 */
	0,	/* long_conv_to_ovf_i2 */
	0,	/* long_conv_to_ovf_u2 */
	0,	/* long_conv_to_ovf_i4 */
	0,	/* long_conv_to_ovf_u4 */
	0,	/* long_conv_to_ovf_i8 */
	0,	/* long_conv_to_ovf_u8 */
	0,	/* long_ceq */
	0,	/* long_cgt */
	0,	/* long_cgt_un */
	0,	/* long_clt */
	0,	/* long_clt_un */
	0,	/* long_conv_to_r_un */
	0,	/* long_conv_to_u */
	0,	/* long_add_imm */
	0,	/* long_sub_imm */
	0,	/* long_mul_imm */
	0,	/* long_and_imm */
	0,	/* long_or_imm */
	0,	/* long_xor_imm */
	0,	/* long_shl_imm */
	0,	/* long_shr_imm */
	0,	/* long_shr_un_imm */
	0,	/* long_div_imm */
	0,	/* long_div_un_imm */
	0,	/* long_rem_imm */
	0,	/* long_rem_un_imm */
	0,	/* long_beq */
	0,	/* long_bge */
	0,	/* long_bgt */
	0,	/* long_ble */
	0,	/* long_blt */
	0,	/* long_bne_un */
	0,	/* long_bge_un */
	0,	/* long_bgt_un */
	0,	/* long_ble_un */
	0,	/* long_blt_un */
	0,	/* long_conv_to_r8_2 */
	0,	/* long_conv_to_r4_2 */
	0,	/* long_conv_to_r_un_2 */
	847,	/* long_conv_to_ovf_i4_2 */
	854,	/* int_add */
	861,	/* int_sub */
	868,	/* int_mul */
	875,	/* int_div */
	882,	/* int_div_un */
	889,	/* int_rem */
	896,	/* int_rem_un */
	903,	/* int_and */
	910,	/* int_or */
	917,	/* int_xor */
	924,	/* int_shl */
	931,	/* int_shr */
	938,	/* int_shr_un */
	945,	/* int_neg */
	952,	/* int_not */
	959,	/* int_conv_to_i1 */
	966,	/* int_conv_to_i2 */
	973,	/* int_conv_to_i4 */
	0,	/* int_conv_to_i8 */
	980,	/* int_conv_to_r4 */
	987,	/* int_conv_to_r8 */
	994,	/* int_conv_to_u4 */
	0,	/* int_conv_to_u8 */
	1001,	/* int_conv_to_r_un */
	0,	/* int_conv_to_u */
	1008,	/* int_conv_to_u2 */
	1015,	/* int_conv_to_u1 */
	0,	/* int_conv_to_i */
	0,	/* int_conv_to_ovf_i */
	0,	/* int_conv_to_ovf_u */
	1022,	/* int_add_ovf */
	1029,	/* int_add_ovf_un */
	1036,	/* int_mul_ovf */
	1043,	/* int_mul_ovf_un */
	1050,	/* int_sub_ovf */
	1057,	/* int_sub_ovf_un */
	0,	/* int_conv_to_ovf_i1_un */
	0,	/* int_conv_to_ovf_i2_un */
	0,	/* int_conv_to_ovf_i4_un */
	0,	/* int_conv_to_ovf_i8_un */
	0,	/* int_conv_to_ovf_u1_un */
	0,	/* int_conv_to_ovf_u2_un */
	0,	/* int_conv_to_ovf_u4_un */
	0,	/* int_conv_to_ovf_u8_un */
	0,	/* int_conv_to_ovf_i_un */
	0,	/* int_conv_to_ovf_u_un */
	0,	/* int_conv_to_ovf_i1 */
	0,	/* int_conv_to_ovf_u1 */
	0,	/* int_conv_to_ovf_i2 */
	0,	/* int_conv_to_ovf_u2 */
	0,	/* int_conv_to_ovf_i4 */
	0,	/* int_conv_to_ovf_u4 */
	0,	/* int_conv_to_ovf_i8 */
	0,	/* int_conv_to_ovf_u8 */
	1064,	/* int_adc */
	1071,	/* int_adc_imm */
	1078,	/* int_sbb */
	1085,	/* int_sbb_imm */
	1092,	/* int_addcc */
	1099,	/* int_subcc */
	1106,	/* int_add_imm */
	1113,	/* int_sub_imm */
	1120,	/* int_mul_imm */
	1127,	/* int_div_imm */
	1134,	/* int_div_un_imm */
	1141,	/* int_rem_imm */
	1148,	/* int_rem_un_imm */
	1155,	/* int_and_imm */
	1162,	/* int_or_imm */
	1169,	/* int_xor_imm */
	1176,	/* int_shl_imm */
	1183,	/* int_shr_imm */
	1190,	/* int_shr_un_imm */
	1197,	/* int_ceq */
	1204,	/* int_cgt */
	1211,	/* int_cgt_un */
	1218,	/* int_clt */
	1225,	/* int_clt_un */
	1232,	/* int_beq */
	1239,	/* int_bge */
	1246,	/* int_bgt */
	1253,	/* int_ble */
	1260,	/* int_blt */
	1267,	/* int_bne_un */
	1274,	/* int_bge_un */
	1281,	/* int_bgt_un */
	1288,	/* int_ble_un */
	1295,	/* int_blt_un */
	1302,	/* float_beq */
	1309,	/* float_bge */
	1316,	/* float_bgt */
	1323,	/* float_ble */
	1330,	/* float_blt */
	1337,	/* float_bne_un */
	1344,	/* float_bge_un */
	1351,	/* float_bgt_un */
	1358,	/* float_ble_un */
	1365,	/* float_blt_un */
	1372,	/* float_add */
	1379,	/* float_sub */
	1386,	/* float_mul */
	1393,	/* float_div */
	1400,	/* float_div_un */
	1407,	/* float_rem */
	1414,	/* float_rem_un */
	1421,	/* float_neg */
	1428,	/* float_not */
	1435,	/* float_conv_to_i1 */
	1442,	/* float_conv_to_i2 */
	1449,	/* float_conv_to_i4 */
	1456,	/* float_conv_to_i8 */
	1463,	/* float_conv_to_r4 */
	0,	/* float_conv_to_r8 */
	1470,	/* float_conv_to_u4 */
	1477,	/* float_conv_to_u8 */
	1484,	/* float_conv_to_u2 */
	1491,	/* float_conv_to_u1 */
	1498,	/* float_conv_to_i */
	0,	/* float_conv_to_ovf_i */
	0,	/* float_conv_to_ovd_u */
	0,	/* float_add_ovf */
	0,	/* float_add_ovf_un */
	0,	/* float_mul_ovf */
	0,	/* float_mul_ovf_un */
	0,	/* float_sub_ovf */
	0,	/* float_sub_ovf_un */
	0,	/* float_conv_to_ovf_i1_un */
	0,	/* float_conv_to_ovf_i2_un */
	0,	/* float_conv_to_ovf_i4_un */
	0,	/* float_conv_to_ovf_i8_un */
	0,	/* float_conv_to_ovf_u1_un */
	0,	/* float_conv_to_ovf_u2_un */
	0,	/* float_conv_to_ovf_u4_un */
	0,	/* float_conv_to_ovf_u8_un */
	0,	/* float_conv_to_ovf_i_un */
	0,	/* float_conv_to_ovf_u_un */
	0,	/* float_conv_to_ovf_i1 */
	0,	/* float_conv_to_ovf_u1 */
	0,	/* float_conv_to_ovf_i2 */
	0,	/* float_conv_to_ovf_u2 */
	0,	/* float_conv_to_ovf_i4 */
	0,	/* float_conv_to_ovf_u4 */
	0,	/* float_conv_to_ovf_i8 */
	0,	/* float_conv_to_ovf_u8 */
	1505,	/* float_ceq */
	1512,	/* float_cgt */
	1519,	/* float_cgt_un */
	1526,	/* float_clt */
	1533,	/* float_clt_un */
	0,	/* float_ceq_membase */
	0,	/* float_cgt_membase */
	0,	/* float_cgt_un_membase */
	0,	/* float_clt_membase */
	0,	/* float_clt_un_membase */
	1540,	/* float_conv_to_u */
	1547,	/* ckfinite */
	0,	/* float_getlow32 */
	0,	/* float_gethigh32 */
	0,	/* jump_table */
	1554,	/* aot_const */
	0,	/* patch_info */
	0,	/* got_entry */
	1561,	/* call_handler */
	1568,	/* start_handler */
	1575,	/* endfilter */
	1582,	/* endfinally */
	1589,	/* bigmul */
	1596,	/* bigmul_un */
	0,	/* int_min_un */
	0,	/* int_max_un */
	0,	/* long_min_un */
	0,	/* long_max_un */
	0,	/* min */
	0,	/* max */
	0,	/* int_min */
	0,	/* int_max */
	0,	/* long_min */
	0,	/* long_max */
	1603,	/* adc */
	1610,	/* adc_imm */
	1617,	/* sbb */
	1624,	/* sbb_imm */
	1631,	/* addcc */
	1638,	/* addcc_imm */
	1645,	/* subcc */
	1652,	/* subcc_imm */
	1659,	/* br_reg */
	0,	/* sext_i1 */
	0,	/* sext_i2 */
	0,	/* sext_i4 */
	0,	/* zext_i1 */
	0,	/* zext_i2 */
	0,	/* zext_i4 */
	0,	/* cne */
	0,	/* trunc_i4 */
	1666,	/* add_ovf_carry */
	1673,	/* sub_ovf_carry */
	1680,	/* add_ovf_un_carry */
	1687,	/* sub_ovf_un_carry */
	0,	/* sin */
	0,	/* cos */
	0,	/* abs */
	0,	/* tan */
	0,	/* atan */
	1694,	/* sqrt */
	0,	/* round */
	0,	/* strlen */
	0,	/* newarr */
	0,	/* ldlen */
	0,	/* bounds_check */
	0,	/* getldelema2 */
	0,	/* memcpy */
	0,	/* memset */
	0,	/* save_lmf */
	0,	/* restore_lmf */
	1701,	/* tls_get */
	0,	/* load_gotaddr */
	1708,	/* dummy_use */
	1715,	/* dummy_store */
	1722,	/* not_reached */
	1729,	/* not_null */
	0,	/* xmove */
	0,	/* xzero */
	0,	/* xphi */
	0,	/* atomic_add_i4 */
	0,	/* atomic_add_new_i4 */
	0,	/* atomic_add_imm_i4 */
	0,	/* atomic_add_imm_new_i4 */
	0,	/* atomic_exchange_i4 */
	0,	/* atomic_add_i8 */
	0,	/* atomic_add_new_i8 */
	0,	/* atomic_add_imm_i8 */
	0,	/* atomic_add_imm_new_i8 */
	0,	/* atomic_exchange_i8 */
	1736,	/* memory_barrier */
	0,	/* atomic_cas_i4 */
	0,	/* atomic_cas_i8 */
	0,	/* cmov_ieq */
	0,	/* cmov_ige */
	0,	/* cmov_igt */
	0,	/* cmov_ile */
	0,	/* cmov_ilt */
	0,	/* cmov_ine_un */
	0,	/* cmov_ige_un */
	0,	/* cmov_igt_un */
	0,	/* cmov_ile_un */
	0,	/* cmov_ilt_un */
	0,	/* cmov_leq */
	0,	/* cmov_lge */
	0,	/* cmov_lgt */
	0,	/* cmov_lle */
	0,	/* cmov_llt */
	0,	/* cmov_lne_un */
	0,	/* cmov_lge_un */
	0,	/* cmov_lgt_un */
	0,	/* cmov_lle_un */
	0,	/* cmov_llt_un */
	0,	/* liverange_start */
	0,	/* liverange_end */
	1743,	/* arm_rsbs_imm */
	1750,	/* arm_rsc_imm */
};

