/* File automatically generated by genmdesc, don't change */

const char arm_cpu_desc [] = {
	"\x0\x0\x0\x0\x0"	/* null entry */
	"\x0" "\x0" "\x0" "\x4" "\x0" ""	/* nop */
	"\x0" "\x0" "\x0" "\x4" "\x0" ""	/* relaxed_nop */
	"\x0" "ii\x4" "\x0" ""	/* compare */
	"\x0" "i\x0" "\xc" "\x0" ""	/* compare_imm */
	"\x0" "ff\xc" "\x0" ""	/* fcompare */
	"\x0" "ii\x4" "\x0" ""	/* icompare */
	"\x0" "i\x0" "\xc" "\x0" ""	/* icompare_imm */
	"\x0" "i\x0" "\xc" "\x0" ""	/* oparglist */
	"\x0" "ii\xc" "\x0" ""	/* setlret */
	"ii\x0" "\x3c" "\x0" ""	/* localloc */
	"\x0" "b\x0" "\x4" "\x0" ""	/* checkthis */
	"\x0" "\x0" "\x0" "\x14" "c"	/* voidcall */
	"\x0" "i\x0" "\x8" "c"	/* voidcall_reg */
	"\x0" "b\x0" "\xc" "c"	/* voidcall_membase */
	"a\x0" "\x0" "\x14" "c"	/* call */
	"ai\x0" "\x8" "c"	/* call_reg */
	"ab\x0" "\xc" "c"	/* call_membase */
	"g\x0" "\x0" "\x14" "c"	/* fcall */
	"gi\x0" "\x8" "c"	/* fcall_reg */
	"gb\x0" "\xc" "c"	/* fcall_membase */
	"l\x0" "\x0" "\x14" "c"	/* lcall */
	"li\x0" "\x8" "c"	/* lcall_reg */
	"lb\x0" "\xc" "c"	/* lcall_membase */
	"\x0" "\x0" "\x0" "\x14" "c"	/* vcall */
	"\x0" "i\x0" "\x8" "c"	/* vcall_reg */
	"\x0" "b\x0" "\xc" "c"	/* vcall_membase */
	"\x0" "\x0" "\x0" "\x14" "c"	/* vcall2 */
	"\x0" "i\x0" "\x8" "c"	/* vcall2_reg */
	"\x0" "b\x0" "\xc" "c"	/* vcall2_membase */
	"i\x0" "\x0" "\x10" "\x0" ""	/* iconst */
	"f\x0" "\x0" "\x14" "\x0" ""	/* r4const */
	"f\x0" "\x0" "\x14" "\x0" ""	/* r8const */
	"\x0" "\x0" "\x0" "\x0" "\x0" ""	/* label */
	"\x0" "i\x0" "\x8" "\x0" ""	/* switch */
	"\x0" "i\x0" "\x18" "\x0" ""	/* throw */
	"\x0" "i\x0" "\x14" "\x0" ""	/* rethrow */
	"bi\x0" "\x14" "\x0" ""	/* store_membase_reg */
	"bi\x0" "\xc" "\x0" ""	/* storei1_membase_reg */
	"bi\x0" "\xc" "\x0" ""	/* storei2_membase_reg */
	"bi\x0" "\x14" "\x0" ""	/* storei4_membase_reg */
	"bi\x0" "\x0" "\x0" ""	/* storei8_membase_reg */
	"bf\x0" "\xc" "\x0" ""	/* storer4_membase_reg */
	"bf\x0" "\x18" "\x0" ""	/* storer8_membase_reg */
	"b\x0" "\x0" "\x14" "\x0" ""	/* store_membase_imm */
	"b\x0" "\x0" "\x14" "\x0" ""	/* storei1_membase_imm */
	"b\x0" "\x0" "\x14" "\x0" ""	/* storei2_membase_imm */
	"b\x0" "\x0" "\x14" "\x0" ""	/* storei4_membase_imm */
	"b\x0" "\x0" "\x0" "\x0" ""	/* storei8_membase_imm */
	"ib\x0" "\x14" "\x0" ""	/* load_membase */
	"ib\x0" "\x4" "\x0" ""	/* loadi1_membase */
	"ib\x0" "\x4" "\x0" ""	/* loadu1_membase */
	"ib\x0" "\x4" "\x0" ""	/* loadi2_membase */
	"ib\x0" "\x4" "\x0" ""	/* loadu2_membase */
	"ib\x0" "\x4" "\x0" ""	/* loadi4_membase */
	"ib\x0" "\x4" "\x0" ""	/* loadu4_membase */
	"ib\x0" "\x0" "\x0" ""	/* loadi8_membase */
	"fb\x0" "\x4" "\x0" ""	/* loadr4_membase */
	"fb\x0" "\x18" "\x0" ""	/* loadr8_membase */
	"ibi\x4" "\x0" ""	/* load_memindex */
	"ibi\x4" "\x0" ""	/* loadi1_memindex */
	"ibi\x4" "\x0" ""	/* loadu1_memindex */
	"ibi\x4" "\x0" ""	/* loadi2_memindex */
	"ibi\x4" "\x0" ""	/* loadu2_memindex */
	"ibi\x4" "\x0" ""	/* loadi4_memindex */
	"ibi\x4" "\x0" ""	/* loadu4_memindex */
	"bii\x4" "\x0" ""	/* store_memindex */
	"bii\x4" "\x0" ""	/* storei1_memindex */
	"bii\x4" "\x0" ""	/* storei2_memindex */
	"bii\x4" "\x0" ""	/* storei4_memindex */
	"i\x0" "\x0" "\x8" "\x0" ""	/* loadu4_mem */
	"ii\x0" "\x4" "\x0" ""	/* move */
	"ff\x0" "\x4" "\x0" ""	/* fmove */
	"ii\x0" "\xc" "\x0" ""	/* add_imm */
	"ii\x0" "\xc" "\x0" ""	/* sub_imm */
	"ii\x0" "\xc" "\x0" ""	/* mul_imm */
	"iii\x14" "\x0" ""	/* div_imm */
	"iii\xc" "\x0" ""	/* div_un_imm */
	"iii\x1c" "\x0" ""	/* rem_imm */
	"iii\x10" "\x0" ""	/* rem_un_imm */
	"ii\x0" "\xc" "\x0" ""	/* and_imm */
	"ii\x0" "\xc" "\x0" ""	/* or_imm */
	"ii\x0" "\xc" "\x0" ""	/* xor_imm */
	"ii\x0" "\x8" "\x0" ""	/* shl_imm */
	"ii\x0" "\x8" "\x0" ""	/* shr_imm */
	"ii\x0" "\x8" "\x0" ""	/* shr_un_imm */
	"\x0" "\x0" "\x0" "\x4" "\x0" ""	/* br */
	"\x0" "\x0" "\x0" "\x5c" "\x0" ""	/* jmp */
	"\x0" "\x0" "\x0" "\x4" "\x0" ""	/* break */
	"i\x0" "\x0" "\xc" "\x0" ""	/* ceq */
	"i\x0" "\x0" "\xc" "\x0" ""	/* cgt */
	"i\x0" "\x0" "\xc" "\x0" ""	/* cgt.un */
	"i\x0" "\x0" "\xc" "\x0" ""	/* clt */
	"i\x0" "\x0" "\xc" "\x0" ""	/* clt.un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_eq */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ge */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_gt */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_le */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_lt */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ne_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ge_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_gt_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_le_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_lt_un */
	"\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_ov */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_no */
	"\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_c */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_nc */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ieq */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ige */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_igt */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ile */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ilt */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ine_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ige_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_igt_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ile_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ilt_un */
	"\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_iov */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ino */
	"\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_ic */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_inc */
	"iii\x1e" "\x0" ""	/* long_conv_to_ovf_i */
	"iii\x24" "\x0" ""	/* long_conv_to_ovf_i4_2 */
	"iii\x4" "\x0" ""	/* int_add */
	"iii\x4" "\x0" ""	/* int_sub */
	"iii\x4" "\x0" ""	/* int_mul */
	"iii\x28" "\x0" ""	/* int_div */
	"iii\x10" "\x0" ""	/* int_div_un */
	"iii\x30" "\x0" ""	/* int_rem */
	"iii\x18" "\x0" ""	/* int_rem_un */
	"iii\x4" "\x0" ""	/* int_and */
	"iii\x4" "\x0" ""	/* int_or */
	"iii\x4" "\x0" ""	/* int_xor */
	"iii\x4" "\x0" ""	/* int_shl */
	"iii\x4" "\x0" ""	/* int_shr */
	"iii\x4" "\x0" ""	/* int_shr_un */
	"ii\x0" "\x4" "\x0" ""	/* int_neg */
	"ii\x0" "\x4" "\x0" ""	/* int_not */
	"ii\x0" "\x8" "\x0" ""	/* int_conv_to_i1 */
	"ii\x0" "\x8" "\x0" ""	/* int_conv_to_i2 */
	"ii\x0" "\x4" "\x0" ""	/* int_conv_to_i4 */
	"fi\x0" "\x24" "\x0" ""	/* int_conv_to_r4 */
	"fi\x0" "\x24" "\x0" ""	/* int_conv_to_r8 */
	"ii\x0" "\x0" "\x0" ""	/* int_conv_to_u4 */
	"fi\x0" "\x38" "\x0" ""	/* int_conv_to_r_un */
	"ii\x0" "\x8" "\x0" ""	/* int_conv_to_u2 */
	"ii\x0" "\x4" "\x0" ""	/* int_conv_to_u1 */
	"iii\x10" "\x0" ""	/* int_add_ovf */
	"iii\x10" "\x0" ""	/* int_add_ovf_un */
	"iii\x10" "\x0" ""	/* int_mul_ovf */
	"iii\x10" "\x0" ""	/* int_mul_ovf_un */
	"iii\x10" "\x0" ""	/* int_sub_ovf */
	"iii\x10" "\x0" ""	/* int_sub_ovf_un */
	"iii\x4" "\x0" ""	/* int_adc */
	"ii\x0" "\xc" "\x0" ""	/* int_adc_imm */
	"iii\x4" "\x0" ""	/* int_sbb */
	"ii\x0" "\xc" "\x0" ""	/* int_sbb_imm */
	"iii\x4" "\x0" ""	/* int_addcc */
	"iii\x4" "\x0" ""	/* int_subcc */
	"ii\x0" "\xc" "\x0" ""	/* int_add_imm */
	"ii\x0" "\xc" "\x0" ""	/* int_sub_imm */
	"ii\x0" "\xc" "\x0" ""	/* int_mul_imm */
	"ii\x0" "\x14" "\x0" ""	/* int_div_imm */
	"ii\x0" "\xc" "\x0" ""	/* int_div_un_imm */
	"ii\x0" "\x1c" "\x0" ""	/* int_rem_imm */
	"ii\x0" "\x10" "\x0" ""	/* int_rem_un_imm */
	"ii\x0" "\xc" "\x0" ""	/* int_and_imm */
	"ii\x0" "\xc" "\x0" ""	/* int_or_imm */
	"ii\x0" "\xc" "\x0" ""	/* int_xor_imm */
	"ii\x0" "\x8" "\x0" ""	/* int_shl_imm */
	"ii\x0" "\x8" "\x0" ""	/* int_shr_imm */
	"ii\x0" "\x8" "\x0" ""	/* int_shr_un_imm */
	"i\x0" "\x0" "\xc" "\x0" ""	/* int_ceq */
	"i\x0" "\x0" "\xc" "\x0" ""	/* int_cgt */
	"i\x0" "\x0" "\xc" "\x0" ""	/* int_cgt_un */
	"i\x0" "\x0" "\xc" "\x0" ""	/* int_clt */
	"i\x0" "\x0" "\xc" "\x0" ""	/* int_clt_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_beq */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bge */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bgt */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ble */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_blt */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bne_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bge_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bgt_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ble_un */
	"\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_blt_un */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_beq */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_bge */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_bgt */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_ble */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_blt */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_bne_un */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_bge_un */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_bgt_un */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_ble_un */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* float_blt_un */
	"fff\x4" "\x0" ""	/* float_add */
	"fff\x4" "\x0" ""	/* float_sub */
	"fff\x4" "\x0" ""	/* float_mul */
	"fff\x4" "\x0" ""	/* float_div */
	"fff\x4" "\x0" ""	/* float_div_un */
	"fff\x10" "\x0" ""	/* float_rem */
	"fff\x10" "\x0" ""	/* float_rem_un */
	"ff\x0" "\x4" "\x0" ""	/* float_neg */
	"ff\x0" "\x4" "\x0" ""	/* float_not */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_i1 */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_i2 */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_i4 */
	"lf\x0" "\x28" "\x0" ""	/* float_conv_to_i8 */
	"ff\x0" "\x4" "\x0" ""	/* float_conv_to_r4 */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_u4 */
	"lf\x0" "\x28" "\x0" ""	/* float_conv_to_u8 */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_u2 */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_u1 */
	"if\x0" "\x28" "\x0" ""	/* float_conv_to_i */
	"iff\x10" "\x0" ""	/* float_ceq */
	"iff\x10" "\x0" ""	/* float_cgt */
	"iff\x14" "\x0" ""	/* float_cgt_un */
	"iff\x10" "\x0" ""	/* float_clt */
	"iff\x14" "\x0" ""	/* float_clt_un */
	"if\x0" "\x24" "\x0" ""	/* float_conv_to_u */
	"ff\x0" "\x40" "\x0" ""	/* ckfinite */
	"i\x0" "\x0" "\x10" "\x0" ""	/* aot_const */
	"\x0" "\x0" "\x0" "\xc" "\x0" ""	/* call_handler */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* start_handler */
	"\x0" "i\x0" "\x10" "\x0" ""	/* endfilter */
	"\x0" "\x0" "\x0" "\x14" "\x0" ""	/* endfinally */
	"lii\x8" "\x0" ""	/* bigmul */
	"lii\x8" "\x0" ""	/* bigmul_un */
	"iii\x4" "\x0" ""	/* adc */
	"ii\x0" "\xc" "\x0" ""	/* adc_imm */
	"iii\x4" "\x0" ""	/* sbb */
	"ii\x0" "\xc" "\x0" ""	/* sbb_imm */
	"iii\x4" "\x0" ""	/* addcc */
	"ii\x0" "\xc" "\x0" ""	/* addcc_imm */
	"iii\x4" "\x0" ""	/* subcc */
	"ii\x0" "\xc" "\x0" ""	/* subcc_imm */
	"\x0" "i\x0" "\x8" "\x0" ""	/* br_reg */
	"iii\x10" "\x0" ""	/* add_ovf_carry */
	"iii\x10" "\x0" ""	/* sub_ovf_carry */
	"iii\x10" "\x0" ""	/* add_ovf_un_carry */
	"iii\x10" "\x0" ""	/* sub_ovf_un_carry */
	"ff\x0" "\x4" "\x0" ""	/* sqrt */
	"i\x0" "\x0" "\x8" "\x0" ""	/* tls_get */
	"\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_store */
	"\x0" "\x0" "\x0" "\x0" "\x0" ""	/* not_reached */
	"\x0" "i\x0" "\x0" "\x0" ""	/* not_null */
	"\x0" "\x0" "\x0" "\x4" "\x0" ""	/* memory_barrier */
	"ii\x0" "\x4" "\x0" ""	/* arm_rsbs_imm */
	"ii\x0" "\x4" "\x0" ""	/* arm_rsc_imm */
};

const guint16 arm_cpu_desc_idx [] = {
	0,	/* load */
	0,	/* ldaddr */
	0,	/* store */
	5,	/* nop */
	0,	/* hard_nop */
	10,	/* relaxed_nop */
	0,	/* phi */
	0,	/* fphi */
	0,	/* vphi */
	15,	/* compare */
	20,	/* compare_imm */
	25,	/* fcompare */
	0,	/* lcompare */
	30,	/* icompare */
	35,	/* icompare_imm */
	0,	/* lcompare_imm */
	0,	/* local */
	0,	/* arg */
	40,	/* oparglist */
	0,	/* outarg_vt */
	0,	/* outarg_vtretaddr */
	0,	/* setfret */
	45,	/* setlret */
	50,	/* localloc */
	0,	/* localloc_imm */
	55,	/* checkthis */
	60,	/* voidcall */
	0,	/* voidcallvirt */
	65,	/* voidcall_reg */
	70,	/* voidcall_membase */
	75,	/* call */
	80,	/* call_reg */
	85,	/* call_membase */
	0,	/* callvirt */
	90,	/* fcall */
	0,	/* fcallvirt */
	95,	/* fcall_reg */
	100,	/* fcall_membase */
	105,	/* lcall */
	0,	/* lcallvirt */
	110,	/* lcall_reg */
	115,	/* lcall_membase */
	120,	/* vcall */
	0,	/* vcallvirt */
	125,	/* vcall_reg */
	130,	/* vcall_membase */
	135,	/* vcall2 */
	140,	/* vcall2_reg */
	145,	/* vcall2_membase */
	150,	/* iconst */
	0,	/* i8const */
	155,	/* r4const */
	160,	/* r8const */
	0,	/* regvar */
	0,	/* regoffset */
	0,	/* vtarg_addr */
	165,	/* label */
	170,	/* switch */
	175,	/* throw */
	180,	/* rethrow */
	185,	/* store_membase_reg */
	190,	/* storei1_membase_reg */
	195,	/* storei2_membase_reg */
	200,	/* storei4_membase_reg */
	205,	/* storei8_membase_reg */
	210,	/* storer4_membase_reg */
	215,	/* storer8_membase_reg */
	220,	/* store_membase_imm */
	225,	/* storei1_membase_imm */
	230,	/* storei2_membase_imm */
	235,	/* storei4_membase_imm */
	240,	/* storei8_membase_imm */
	0,	/* storex_membase */
	0,	/* storev_membase */
	245,	/* load_membase */
	250,	/* loadi1_membase */
	255,	/* loadu1_membase */
	260,	/* loadi2_membase */
	265,	/* loadu2_membase */
	270,	/* loadi4_membase */
	275,	/* loadu4_membase */
	280,	/* loadi8_membase */
	285,	/* loadr4_membase */
	290,	/* loadr8_membase */
	0,	/* loadx_membase */
	0,	/* loadv_membase */
	295,	/* load_memindex */
	300,	/* loadi1_memindex */
	305,	/* loadu1_memindex */
	310,	/* loadi2_memindex */
	315,	/* loadu2_memindex */
	320,	/* loadi4_memindex */
	325,	/* loadu4_memindex */
	0,	/* loadi8_memindex */
	0,	/* loadr4_memindex */
	0,	/* loadr8_memindex */
	330,	/* store_memindex */
	335,	/* storei1_memindex */
	340,	/* storei2_memindex */
	345,	/* storei4_memindex */
	0,	/* storei8_memindex */
	0,	/* storer4_memindex */
	0,	/* storer8_memindex */
	0,	/* loadr8_spill_membase */
	0,	/* load_mem */
	0,	/* loadu1_mem */
	0,	/* loadu2_mem */
	0,	/* loadi4_mem */
	350,	/* loadu4_mem */
	0,	/* loadi8_mem */
	0,	/* store_mem_imm */
	355,	/* move */
	0,	/* lmove */
	360,	/* fmove */
	0,	/* vmove */
	0,	/* vzero */
	365,	/* add_imm */
	370,	/* sub_imm */
	375,	/* mul_imm */
	380,	/* div_imm */
	385,	/* div_un_imm */
	390,	/* rem_imm */
	395,	/* rem_un_imm */
	400,	/* and_imm */
	405,	/* or_imm */
	410,	/* xor_imm */
	415,	/* shl_imm */
	420,	/* shr_imm */
	425,	/* shr_un_imm */
	430,	/* br */
	435,	/* jmp */
	0,	/* tailcall */
	440,	/* break */
	445,	/* ceq */
	450,	/* cgt */
	455,	/* cgt.un */
	460,	/* clt */
	465,	/* clt.un */
	470,	/* cond_exc_eq */
	475,	/* cond_exc_ge */
	480,	/* cond_exc_gt */
	485,	/* cond_exc_le */
	490,	/* cond_exc_lt */
	495,	/* cond_exc_ne_un */
	500,	/* cond_exc_ge_un */
	505,	/* cond_exc_gt_un */
	510,	/* cond_exc_le_un */
	515,	/* cond_exc_lt_un */
	520,	/* cond_exc_ov */
	525,	/* cond_exc_no */
	530,	/* cond_exc_c */
	535,	/* cond_exc_nc */
	540,	/* cond_exc_ieq */
	545,	/* cond_exc_ige */
	550,	/* cond_exc_igt */
	555,	/* cond_exc_ile */
	560,	/* cond_exc_ilt */
	565,	/* cond_exc_ine_un */
	570,	/* cond_exc_ige_un */
	575,	/* cond_exc_igt_un */
	580,	/* cond_exc_ile_un */
	585,	/* cond_exc_ilt_un */
	590,	/* cond_exc_iov */
	595,	/* cond_exc_ino */
	600,	/* cond_exc_ic */
	605,	/* cond_exc_inc */
	0,	/* long_add */
	0,	/* long_sub */
	0,	/* long_mul */
	0,	/* long_div */
	0,	/* long_div_un */
	0,	/* long_rem */
	0,	/* long_rem_un */
	0,	/* long_and */
	0,	/* long_or */
	0,	/* long_xor */
	0,	/* long_shl */
	0,	/* long_shr */
	0,	/* long_shr_un */
	0,	/* long_neg */
	0,	/* long_not */
	0,	/* long_conv_to_i1 */
	0,	/* long_conv_to_i2 */
	0,	/* long_conv_to_i4 */
	0,	/* long_conv_to_i8 */
	0,	/* long_conv_to_r4 */
	0,	/* long_conv_to_r8 */
	0,	/* long_conv_to_u4 */
	0,	/* long_conv_to_u8 */
	0,	/* long_conv_to_u2 */
	0,	/* long_conv_to_u1 */
	0,	/* long_conv_to_i */
	610,	/* long_conv_to_ovf_i */
	0,	/* long_conv_to_ovf_u */
	0,	/* long_add_ovf */
	0,	/* long_add_ovf_un */
	0,	/* long_mul_ovf */
	0,	/* long_mul_ovf_un */
	0,	/* long_sub_ovf */
	0,	/* long_sub_ovf_un */
	0,	/* long_conv_to_ovf_i1_un */
	0,	/* long_conv_to_ovf_i2_un */
	0,	/* long_conv_to_ovf_i4_un */
	0,	/* long_conv_to_ovf_i8_un */
	0,	/* long_conv_to_ovf_u1_un */
	0,	/* long_conv_to_ovf_u2_un */
	0,	/* long_conv_to_ovf_u4_un */
	0,	/* long_conv_to_ovf_u8_un */
	0,	/* long_conv_to_ovf_i_un */
	0,	/* long_conv_to_ovf_u_un */
	0,	/* long_conv_to_ovf_i1 */
	0,	/* long_conv_to_ovf_u1 */
	0,	/* long_conv_to_ovf_i2 */
	0,	/* long_conv_to_ovf_u2 */
	0,	/* long_conv_to_ovf_i4 */
	0,	/* long_conv_to_ovf_u4 */
	0,	/* long_conv_to_ovf_i8 */
	0,	/* long_conv_to_ovf_u8 */
	0,	/* long_ceq */
	0,	/* long_cgt */
	0,	/* long_cgt_un */
	0,	/* long_clt */
	0,	/* long_clt_un */
	0,	/* long_conv_to_r_un */
	0,	/* long_conv_to_u */
	0,	/* long_add_imm */
	0,	/* long_sub_imm */
	0,	/* long_mul_imm */
	0,	/* long_and_imm */
	0,	/* long_or_imm */
	0,	/* long_xor_imm */
	0,	/* long_shl_imm */
	0,	/* long_shr_imm */
	0,	/* long_shr_un_imm */
	0,	/* long_div_imm */
	0,	/* long_div_un_imm */
	0,	/* long_rem_imm */
	0,	/* long_rem_un_imm */
	0,	/* long_beq */
	0,	/* long_bge */
	0,	/* long_bgt */
	0,	/* long_ble */
	0,	/* long_blt */
	0,	/* long_bne_un */
	0,	/* long_bge_un */
	0,	/* long_bgt_un */
	0,	/* long_ble_un */
	0,	/* long_blt_un */
	0,	/* long_conv_to_r8_2 */
	0,	/* long_conv_to_r4_2 */
	0,	/* long_conv_to_r_un_2 */
	615,	/* long_conv_to_ovf_i4_2 */
	620,	/* int_add */
	625,	/* int_sub */
	630,	/* int_mul */
	635,	/* int_div */
	640,	/* int_div_un */
	645,	/* int_rem */
	650,	/* int_rem_un */
	655,	/* int_and */
	660,	/* int_or */
	665,	/* int_xor */
	670,	/* int_shl */
	675,	/* int_shr */
	680,	/* int_shr_un */
	685,	/* int_neg */
	690,	/* int_not */
	695,	/* int_conv_to_i1 */
	700,	/* int_conv_to_i2 */
	705,	/* int_conv_to_i4 */
	0,	/* int_conv_to_i8 */
	710,	/* int_conv_to_r4 */
	715,	/* int_conv_to_r8 */
	720,	/* int_conv_to_u4 */
	0,	/* int_conv_to_u8 */
	725,	/* int_conv_to_r_un */
	0,	/* int_conv_to_u */
	730,	/* int_conv_to_u2 */
	735,	/* int_conv_to_u1 */
	0,	/* int_conv_to_i */
	0,	/* int_conv_to_ovf_i */
	0,	/* int_conv_to_ovf_u */
	740,	/* int_add_ovf */
	745,	/* int_add_ovf_un */
	750,	/* int_mul_ovf */
	755,	/* int_mul_ovf_un */
	760,	/* int_sub_ovf */
	765,	/* int_sub_ovf_un */
	0,	/* int_conv_to_ovf_i1_un */
	0,	/* int_conv_to_ovf_i2_un */
	0,	/* int_conv_to_ovf_i4_un */
	0,	/* int_conv_to_ovf_i8_un */
	0,	/* int_conv_to_ovf_u1_un */
	0,	/* int_conv_to_ovf_u2_un */
	0,	/* int_conv_to_ovf_u4_un */
	0,	/* int_conv_to_ovf_u8_un */
	0,	/* int_conv_to_ovf_i_un */
	0,	/* int_conv_to_ovf_u_un */
	0,	/* int_conv_to_ovf_i1 */
	0,	/* int_conv_to_ovf_u1 */
	0,	/* int_conv_to_ovf_i2 */
	0,	/* int_conv_to_ovf_u2 */
	0,	/* int_conv_to_ovf_i4 */
	0,	/* int_conv_to_ovf_u4 */
	0,	/* int_conv_to_ovf_i8 */
	0,	/* int_conv_to_ovf_u8 */
	770,	/* int_adc */
	775,	/* int_adc_imm */
	780,	/* int_sbb */
	785,	/* int_sbb_imm */
	790,	/* int_addcc */
	795,	/* int_subcc */
	800,	/* int_add_imm */
	805,	/* int_sub_imm */
	810,	/* int_mul_imm */
	815,	/* int_div_imm */
	820,	/* int_div_un_imm */
	825,	/* int_rem_imm */
	830,	/* int_rem_un_imm */
	835,	/* int_and_imm */
	840,	/* int_or_imm */
	845,	/* int_xor_imm */
	850,	/* int_shl_imm */
	855,	/* int_shr_imm */
	860,	/* int_shr_un_imm */
	865,	/* int_ceq */
	870,	/* int_cgt */
	875,	/* int_cgt_un */
	880,	/* int_clt */
	885,	/* int_clt_un */
	890,	/* int_beq */
	895,	/* int_bge */
	900,	/* int_bgt */
	905,	/* int_ble */
	910,	/* int_blt */
	915,	/* int_bne_un */
	920,	/* int_bge_un */
	925,	/* int_bgt_un */
	930,	/* int_ble_un */
	935,	/* int_blt_un */
	940,	/* float_beq */
	945,	/* float_bge */
	950,	/* float_bgt */
	955,	/* float_ble */
	960,	/* float_blt */
	965,	/* float_bne_un */
	970,	/* float_bge_un */
	975,	/* float_bgt_un */
	980,	/* float_ble_un */
	985,	/* float_blt_un */
	990,	/* float_add */
	995,	/* float_sub */
	1000,	/* float_mul */
	1005,	/* float_div */
	1010,	/* float_div_un */
	1015,	/* float_rem */
	1020,	/* float_rem_un */
	1025,	/* float_neg */
	1030,	/* float_not */
	1035,	/* float_conv_to_i1 */
	1040,	/* float_conv_to_i2 */
	1045,	/* float_conv_to_i4 */
	1050,	/* float_conv_to_i8 */
	1055,	/* float_conv_to_r4 */
	0,	/* float_conv_to_r8 */
	1060,	/* float_conv_to_u4 */
	1065,	/* float_conv_to_u8 */
	1070,	/* float_conv_to_u2 */
	1075,	/* float_conv_to_u1 */
	1080,	/* float_conv_to_i */
	0,	/* float_conv_to_ovf_i */
	0,	/* float_conv_to_ovd_u */
	0,	/* float_add_ovf */
	0,	/* float_add_ovf_un */
	0,	/* float_mul_ovf */
	0,	/* float_mul_ovf_un */
	0,	/* float_sub_ovf */
	0,	/* float_sub_ovf_un */
	0,	/* float_conv_to_ovf_i1_un */
	0,	/* float_conv_to_ovf_i2_un */
	0,	/* float_conv_to_ovf_i4_un */
	0,	/* float_conv_to_ovf_i8_un */
	0,	/* float_conv_to_ovf_u1_un */
	0,	/* float_conv_to_ovf_u2_un */
	0,	/* float_conv_to_ovf_u4_un */
	0,	/* float_conv_to_ovf_u8_un */
	0,	/* float_conv_to_ovf_i_un */
	0,	/* float_conv_to_ovf_u_un */
	0,	/* float_conv_to_ovf_i1 */
	0,	/* float_conv_to_ovf_u1 */
	0,	/* float_conv_to_ovf_i2 */
	0,	/* float_conv_to_ovf_u2 */
	0,	/* float_conv_to_ovf_i4 */
	0,	/* float_conv_to_ovf_u4 */
	0,	/* float_conv_to_ovf_i8 */
	0,	/* float_conv_to_ovf_u8 */
	1085,	/* float_ceq */
	1090,	/* float_cgt */
	1095,	/* float_cgt_un */
	1100,	/* float_clt */
	1105,	/* float_clt_un */
	0,	/* float_ceq_membase */
	0,	/* float_cgt_membase */
	0,	/* float_cgt_un_membase */
	0,	/* float_clt_membase */
	0,	/* float_clt_un_membase */
	1110,	/* float_conv_to_u */
	1115,	/* ckfinite */
	0,	/* float_getlow32 */
	0,	/* float_gethigh32 */
	0,	/* jump_table */
	1120,	/* aot_const */
	0,	/* patch_info */
	0,	/* got_entry */
	1125,	/* call_handler */
	1130,	/* start_handler */
	1135,	/* endfilter */
	1140,	/* endfinally */
	1145,	/* bigmul */
	1150,	/* bigmul_un */
	0,	/* int_min_un */
	0,	/* int_max_un */
	0,	/* long_min_un */
	0,	/* long_max_un */
	0,	/* min */
	0,	/* max */
	0,	/* int_min */
	0,	/* int_max */
	0,	/* long_min */
	0,	/* long_max */
	1155,	/* adc */
	1160,	/* adc_imm */
	1165,	/* sbb */
	1170,	/* sbb_imm */
	1175,	/* addcc */
	1180,	/* addcc_imm */
	1185,	/* subcc */
	1190,	/* subcc_imm */
	1195,	/* br_reg */
	0,	/* sext_i1 */
	0,	/* sext_i2 */
	0,	/* sext_i4 */
	0,	/* zext_i1 */
	0,	/* zext_i2 */
	0,	/* zext_i4 */
	0,	/* cne */
	1200,	/* add_ovf_carry */
	1205,	/* sub_ovf_carry */
	1210,	/* add_ovf_un_carry */
	1215,	/* sub_ovf_un_carry */
	0,	/* sin */
	0,	/* cos */
	0,	/* abs */
	0,	/* tan */
	0,	/* atan */
	1220,	/* sqrt */
	0,	/* round */
	0,	/* strlen */
	0,	/* newarr */
	0,	/* ldlen */
	0,	/* bounds_check */
	0,	/* getldelema2 */
	0,	/* memcpy */
	0,	/* memset */
	0,	/* save_lmf */
	0,	/* restore_lmf */
	1225,	/* tls_get */
	0,	/* load_gotaddr */
	1230,	/* dummy_use */
	1235,	/* dummy_store */
	1240,	/* not_reached */
	1245,	/* not_null */
	0,	/* xmove */
	0,	/* xzero */
	0,	/* xphi */
	0,	/* atomic_add_i4 */
	0,	/* atomic_add_new_i4 */
	0,	/* atomic_add_imm_i4 */
	0,	/* atomic_add_imm_new_i4 */
	0,	/* atomic_exchange_i4 */
	0,	/* atomic_add_i8 */
	0,	/* atomic_add_new_i8 */
	0,	/* atomic_add_imm_i8 */
	0,	/* atomic_add_imm_new_i8 */
	0,	/* atomic_exchange_i8 */
	1250,	/* memory_barrier */
	0,	/* atomic_cas_imm_i4 */
	0,	/* atomic_cas_imm_i8 */
	0,	/* cmov_ieq */
	0,	/* cmov_ige */
	0,	/* cmov_igt */
	0,	/* cmov_ile */
	0,	/* cmov_ilt */
	0,	/* cmov_ine_un */
	0,	/* cmov_ige_un */
	0,	/* cmov_igt_un */
	0,	/* cmov_ile_un */
	0,	/* cmov_ilt_un */
	0,	/* cmov_leq */
	0,	/* cmov_lge */
	0,	/* cmov_lgt */
	0,	/* cmov_lle */
	0,	/* cmov_llt */
	0,	/* cmov_lne_un */
	0,	/* cmov_lge_un */
	0,	/* cmov_lgt_un */
	0,	/* cmov_lle_un */
	0,	/* cmov_llt_un */
	0,	/* liverange_start */
	0,	/* liverange_end */
	1255,	/* arm_rsbs_imm */
	1260,	/* arm_rsc_imm */
};

