namespace javax.microedition.khronos.opengles 
{ 
	[global::net.sf.jni4net.attributes.JavaInterfaceAttribute()] 
	public interface GL10 : GL
	{ 
		void glActiveTexture(int arg0); 
		void glAlphaFunc(int arg0, float arg1); 
		void glAlphaFuncx(int arg0, int arg1); 
		void glBindTexture(int arg0, int arg1); 
		void glBlendFunc(int arg0, int arg1); 
		void glClear(int arg0); 
		void glClearColor(float arg0, float arg1, float arg2, float arg3); 
		void glClearColorx(int arg0, int arg1, int arg2, int arg3); 
		void glClearDepthf(float arg0); 
		void glClearDepthx(int arg0); 
		void glClearStencil(int arg0); 
		void glClientActiveTexture(int arg0); 
		void glColor4f(float arg0, float arg1, float arg2, float arg3); 
		void glColor4x(int arg0, int arg1, int arg2, int arg3); 
		void glColorMask(bool arg0, bool arg1, bool arg2, bool arg3); 
		void glColorPointer(int arg0, int arg1, int arg2, java.nio.Buffer arg3); 
		void glCompressedTexImage2D(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, java.nio.Buffer arg7); 
		void glCompressedTexSubImage2D(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, java.nio.Buffer arg8); 
		void glCopyTexImage2D(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7); 
		void glCopyTexSubImage2D(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7); 
		void glCullFace(int arg0); 
		void glDeleteTextures(int arg0, int[] arg1, int arg2); 
		void glDeleteTextures(int arg0, java.nio.IntBuffer arg1); 
		void glDepthFunc(int arg0); 
		void glDepthMask(bool arg0); 
		void glDepthRangef(float arg0, float arg1); 
		void glDepthRangex(int arg0, int arg1); 
		void glDisable(int arg0); 
		void glDisableClientState(int arg0); 
		void glDrawArrays(int arg0, int arg1, int arg2); 
		void glDrawElements(int arg0, int arg1, int arg2, java.nio.Buffer arg3); 
		void glEnable(int arg0); 
		void glEnableClientState(int arg0); 
		void glFinish(); 
		void glFlush(); 
		void glFogf(int arg0, float arg1); 
		void glFogfv(int arg0, float[] arg1, int arg2); 
		void glFogfv(int arg0, java.nio.FloatBuffer arg1); 
		void glFogx(int arg0, int arg1); 
		void glFogxv(int arg0, int[] arg1, int arg2); 
		void glFogxv(int arg0, java.nio.IntBuffer arg1); 
		void glFrontFace(int arg0); 
		void glFrustumf(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5); 
		void glFrustumx(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5); 
		void glGenTextures(int arg0, int[] arg1, int arg2); 
		void glGenTextures(int arg0, java.nio.IntBuffer arg1); 
		int glGetError(); 
		void glGetIntegerv(int arg0, int[] arg1, int arg2); 
		void glGetIntegerv(int arg0, java.nio.IntBuffer arg1); 
		java.lang.String glGetString(int arg0); 
		void glHint(int arg0, int arg1); 
		void glLightModelf(int arg0, float arg1); 
		void glLightModelfv(int arg0, float[] arg1, int arg2); 
		void glLightModelfv(int arg0, java.nio.FloatBuffer arg1); 
		void glLightModelx(int arg0, int arg1); 
		void glLightModelxv(int arg0, int[] arg1, int arg2); 
		void glLightModelxv(int arg0, java.nio.IntBuffer arg1); 
		void glLightf(int arg0, int arg1, float arg2); 
		void glLightfv(int arg0, int arg1, float[] arg2, int arg3); 
		void glLightfv(int arg0, int arg1, java.nio.FloatBuffer arg2); 
		void glLightx(int arg0, int arg1, int arg2); 
		void glLightxv(int arg0, int arg1, int[] arg2, int arg3); 
		void glLightxv(int arg0, int arg1, java.nio.IntBuffer arg2); 
		void glLineWidth(float arg0); 
		void glLineWidthx(int arg0); 
		void glLoadIdentity(); 
		void glLoadMatrixf(float[] arg0, int arg1); 
		void glLoadMatrixf(java.nio.FloatBuffer arg0); 
		void glLoadMatrixx(int[] arg0, int arg1); 
		void glLoadMatrixx(java.nio.IntBuffer arg0); 
		void glLogicOp(int arg0); 
		void glMaterialf(int arg0, int arg1, float arg2); 
		void glMaterialfv(int arg0, int arg1, float[] arg2, int arg3); 
		void glMaterialfv(int arg0, int arg1, java.nio.FloatBuffer arg2); 
		void glMaterialx(int arg0, int arg1, int arg2); 
		void glMaterialxv(int arg0, int arg1, int[] arg2, int arg3); 
		void glMaterialxv(int arg0, int arg1, java.nio.IntBuffer arg2); 
		void glMatrixMode(int arg0); 
		void glMultMatrixf(float[] arg0, int arg1); 
		void glMultMatrixf(java.nio.FloatBuffer arg0); 
		void glMultMatrixx(int[] arg0, int arg1); 
		void glMultMatrixx(java.nio.IntBuffer arg0); 
		void glMultiTexCoord4f(int arg0, float arg1, float arg2, float arg3, float arg4); 
		void glMultiTexCoord4x(int arg0, int arg1, int arg2, int arg3, int arg4); 
		void glNormal3f(float arg0, float arg1, float arg2); 
		void glNormal3x(int arg0, int arg1, int arg2); 
		void glNormalPointer(int arg0, int arg1, java.nio.Buffer arg2); 
		void glOrthof(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5); 
		void glOrthox(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5); 
		void glPixelStorei(int arg0, int arg1); 
		void glPointSize(float arg0); 
		void glPointSizex(int arg0); 
		void glPolygonOffset(float arg0, float arg1); 
		void glPolygonOffsetx(int arg0, int arg1); 
		void glPopMatrix(); 
		void glPushMatrix(); 
		void glReadPixels(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, java.nio.Buffer arg6); 
		void glRotatef(float arg0, float arg1, float arg2, float arg3); 
		void glRotatex(int arg0, int arg1, int arg2, int arg3); 
		void glSampleCoverage(float arg0, bool arg1); 
		void glSampleCoveragex(int arg0, bool arg1); 
		void glScalef(float arg0, float arg1, float arg2); 
		void glScalex(int arg0, int arg1, int arg2); 
		void glScissor(int arg0, int arg1, int arg2, int arg3); 
		void glShadeModel(int arg0); 
		void glStencilFunc(int arg0, int arg1, int arg2); 
		void glStencilMask(int arg0); 
		void glStencilOp(int arg0, int arg1, int arg2); 
		void glTexCoordPointer(int arg0, int arg1, int arg2, java.nio.Buffer arg3); 
		void glTexEnvf(int arg0, int arg1, float arg2); 
		void glTexEnvfv(int arg0, int arg1, float[] arg2, int arg3); 
		void glTexEnvfv(int arg0, int arg1, java.nio.FloatBuffer arg2); 
		void glTexEnvx(int arg0, int arg1, int arg2); 
		void glTexEnvxv(int arg0, int arg1, int[] arg2, int arg3); 
		void glTexEnvxv(int arg0, int arg1, java.nio.IntBuffer arg2); 
		void glTexImage2D(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, java.nio.Buffer arg8); 
		void glTexParameterf(int arg0, int arg1, float arg2); 
		void glTexParameterx(int arg0, int arg1, int arg2); 
		void glTexSubImage2D(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, java.nio.Buffer arg8); 
		void glTranslatef(float arg0, float arg1, float arg2); 
		void glTranslatex(int arg0, int arg1, int arg2); 
		void glVertexPointer(int arg0, int arg1, int arg2, java.nio.Buffer arg3); 
		void glViewport(int arg0, int arg1, int arg2, int arg3); 
	} 
} 
