/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_koushikdutta_monojavabridge_MonoBridge */

#ifndef _Included_com_koushikdutta_monojavabridge_MonoBridge
#define _Included_com_koushikdutta_monojavabridge_MonoBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_koushikdutta_monojavabridge_MonoBridge
 * Method:    prelink
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_koushikdutta_monojavabridge_MonoBridge_prelink
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_koushikdutta_monojavabridge_MonoBridge
 * Method:    loadAssembly
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_koushikdutta_monojavabridge_MonoBridge_loadAssembly
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
