#!/bin/sh
cd ../MonoActivity/assets/assets/
ASSEMBLIES=$(find . -name *.dll)
echo $ASSEMBLIES
for assembly in $ASSEMBLIES
do
	echo Processing $assembly...
	adb shell HOME=/data/local /data/data/com.koushikdutta.mono/mono --aot=asmonly /data/data/com.koushikdutta.mono/assets/$assembly
	adb pull /data/data/com.koushikdutta.mono/assets/$assembly.s ../../../aot
done
