/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

namespace com.koushikdutta.twitter
{

public static class R {
    public static class attr {
    }
    public static class drawable {
        public static readonly int icon=0x7f020000;
    }
    public static class string_ {
        public static readonly int app_name=0x7f030000;
    }
}

}